### ISSUE TITLE
Publish to Crates?

### ISSUE THREAD

**Issue by alexanderdean** [rsolomo/hipchat-client#1]
Would you be willing to publish this to Crates?

https://crates.io/search?q=hipchat-client

**Comment by rsolomo** [comment]
Short answer:

Yes, if this is useful, publishing to crates.io can be done.

Long answer:
I had not published this yet because it is very much a work in-progress.
I'm currently running into situations where the JSON in the HipChat API contains undocumented properties, which will in turn result in tripping over serde-rs/serde/issues/44.

This can be replicated by running the integration tests. I get the following error:

```
thread 'integration_get_room' panicked at 'called `Result::unwrap()` on an `Err` value: Json(SyntaxError(unknown field "last_active", 1, 162))', ../src/libcore/result.rs:688
```

Even though there is no mention of `last_active` in the HipChat API documentation: https://www.hipchat.com/docs/apiv2/method/get_room.

...maybe I should just switch back to rustc_serialize for now :disappointed:.

**Comment by alexanderdean** [comment]
Hey @rsolomo - thanks for the detailed response during the holidays!

Frustrating about the additional properties - selfishly, I know that this library would be useful on Crates in its current form for me, as I want to use it primarily for posting notifications to rooms.

Anyway, will await your decision :mortar_board:

**Comment by rsolomo** [comment]
Okay, this is uploaded to crates.io now: https://crates.io/crates/hipchat-client

**Comment by alexanderdean** [comment]
Thanks so much Ray!
